// <auto-generated />
using System;
using InformaticaMp.Api.Inventario.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace InformaticaMp.Api.Inventario.Migrations
{
    [DbContext(typeof(ContextoPersonalMp))]
    [Migration("20220316181105_MigracionPostgresInicial")]
    partial class MigracionPostgresInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("InformaticaMp.Api.Inventario.Modelo.BienInformatico", b =>
                {
                    b.Property<int>("BienInformaticoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BienInformaticoGuid")
                        .HasColumnType("text");

                    b.Property<string>("CodigoInventario")
                        .HasColumnType("text");

                    b.Property<string>("CodigoPatrimonial")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("DiscoDuro")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("EstadoBien")
                        .HasColumnType("text");

                    b.Property<string>("FuncionEquipo")
                        .HasColumnType("text");

                    b.Property<string>("Ip")
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .HasColumnType("text");

                    b.Property<string>("MemoriaGB")
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .HasColumnType("text");

                    b.Property<int>("PersonalMpId")
                        .HasColumnType("integer");

                    b.Property<string>("Procesador")
                        .HasColumnType("text");

                    b.Property<string>("Serie")
                        .HasColumnType("text");

                    b.Property<string>("TipoBien")
                        .HasColumnType("text");

                    b.Property<string>("TipoImpresion")
                        .HasColumnType("text");

                    b.Property<string>("TipoSoftware")
                        .HasColumnType("text");

                    b.HasKey("BienInformaticoId");

                    b.HasIndex("PersonalMpId");

                    b.ToTable("BienInformatico");
                });

            modelBuilder.Entity("InformaticaMp.Api.Inventario.Modelo.PersonalMp", b =>
                {
                    b.Property<int>("PersonalMpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Apellidos")
                        .HasColumnType("text");

                    b.Property<string>("AreaDespacho")
                        .HasColumnType("text");

                    b.Property<string>("Cargo")
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .HasColumnType("text");

                    b.Property<string>("DespachoAnterior")
                        .HasColumnType("text");

                    b.Property<string>("DistritoFiscal")
                        .HasColumnType("text");

                    b.Property<string>("Dni")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Local")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("PersonalMpGuid")
                        .HasColumnType("text");

                    b.Property<string>("RegimenLaboral")
                        .HasColumnType("text");

                    b.Property<string>("Sede")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("PersonalMpId");

                    b.ToTable("PersonalMp");
                });

            modelBuilder.Entity("InformaticaMp.Api.Inventario.Modelo.BienInformatico", b =>
                {
                    b.HasOne("InformaticaMp.Api.Inventario.Modelo.PersonalMp", "PersonalMp")
                        .WithMany("ListabienInformaticos")
                        .HasForeignKey("PersonalMpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
